[build]
  base = "frontend"  # Change base to frontend since that's where your frontend lives
  command = "npm run build"
  publish = "dist"  # This is the output directory for Vite

[functions]
  directory = "../backend/api/netlify/functions"  # Correct path to functions
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200