[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "backend/api/netlify/functions"  
  external_node_modules = ["express", "mongoose", "multer", "cloudinary", "streamifier", "cors", "body-parser", "serverless-http", "dotenv"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[context.production]
  ENVIRONMENT = "production"

[context.deploy-preview]
  ENVIRONMENT = "deploy-preview"

[context.branch-deploy]
  ENVIRONMENT = "branch-deploy"

[context.dev]
  ENVIRONMENT = "development"
