[build]
  functions = "backend/api/netlify/functions"
  command = "npm run build"
  publish = ".next"
  
[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[images]
  remote_images = ["https://nw-builds.netlify.app/.netlify/images/*"] 